name: light_house
description: "Flutter BLE project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  collection: any
  material_color_utilities: any

  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  flutter_mobx: ^2.2.0+2
  flutter_reactive_ble: ^5.3.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  mobx: ^2.3.0+1
  shared_preferences: ^2.2.2
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  widgetbook_generator: ^3.7.0

  ross_lints:
    git:
      url: https://github.com/RossHS/ross_lint_ruleset

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
