name: light_house_web_demo_app
description: "Light house. Demo App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.19.0


dependencies:
  flutter:
    sdk: flutter

  light_house:
    path:
      ../../flutter_source
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  ross_lints:
    git:
      url: https://github.com/RossHS/ross_lint_ruleset

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/glitch.glsl

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf