name: light_house
description: "Flutter BLE project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  async: any
  collection: any
  material_color_utilities: any

  # К сожалению, проект устарел и проект не будет собираться
  # из-за старых стилей в библиотеке по типу bodyText1
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: 92bdb69
  flutter_mobx: ^2.2.1+1
  flutter_reactive_ble: ^5.3.1
  flutter_shaders: ^0.1.2
  get_it: ^7.6.9
  go_router: ^13.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.2.0
  mobx: ^2.3.3+2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^8.0.3
  shared_preferences: ^2.2.3
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.6.1
  widgetbook_generator: ^3.7.0

  ross_lints:
    git:
      url: https://github.com/RossHS/ross_lint_ruleset

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/glitch.glsl

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"